### ISSUE TITLE
States are allowed to transition into themselves by default.

### ISSUE THREAD

**Issue by merrickheley** [eonarheim/TypeState#16]
I was checking out this library and I noticed that by default states are able to transition into themselves, even if an explicit transition from the state to itself has not been defined. I can't see any way to turn this off.

Is there a particular reason why this design choice was made? It seems bad practice to allow for transitions that aren't explicitly defined by the users because:

- For people who haven't seen the library before it's not obvious as to what the code is doing.
- This isn't always a desired outcome in code. To use the example in the readme: If entering the ElevatorClosed state causes the control system to drive the actuator that closes the doors, re-entering the state may damage the actuator.

Surely there's a way of creating a function or option that allows for users to control whether states can re-enter by default?

**Comment by eonarheim** [comment]
I totally agree, I believe it would be beat to have an explicit transition
declared for same to same state transitions. That's how FSMs in automata
theory work.

This feels like a bug for sure, and fortunately easy to write a test for. I
won't have too much time to work on this right now, if you're up to it I'd
be more than willing to accept a PR. Perhaps adding an option like
"allowImplicitSelfTransition" to preserve backwards compatibility. It would
be more correct to default it to false to match FSMs accurately

**Comment by merrickheley** [comment]
I've made a pull request to resolve this. As noted in the pull request it's worth checking this properly as I haven't got much experience with typescript.

I didn't include any of the generated dist files in the commit as I'm not sure what your procedure is on this.

If this is accepted, how long before any changes are able to be seen in NuGet?
