### ISSUE TITLE
Compile errors with TypeScript 2.4

### ISSUE THREAD

**Issue by MattKyle** [eonarheim/TypeState#18]
I get compile errors when using TypeScript 2.4 that aren't present using 2.3

message: 'Argument of type '(accum: boolean, next: () => boolean) => boolean' is not assignable to parameter of type '(previousValue: boolean, currentValue: (to: T) => boolean, currentIndex: number, array: ((to: T) ...'.
  Types of parameters 'next' and 'currentValue' are incompatible.'
at: '217,90'
source: 'ts'

Possibly to do with the "Improved inference for generics".
See: http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html

**Comment by eonarheim** [comment]
@MattKyle Thanks! That is indeed the problem, I've made a fix please let me know if this works for you in master.

**Comment by MattKyle** [comment]
Yes, that fixes it. Thanks for the fast response.

**Comment by eonarheim** [comment]
I'll have some free time soon to cut the new NPM and Bower packages,

Cheers!
Erik

**Comment by HarryPi** [comment]
Hi, having same issue when downloading with npm. Npm indicates lattest is 1.0.4 and now 1.0.5 where this issue was committed as fix.
Thanks.

**Comment by eonarheim** [comment]
@HarryPi Indeed you are right, I've published 1.0.5 now let me know if you have issues
