### ISSUE TITLE
Dependency vulnurabilities

### ISSUE THREAD

**Issue by hershal** [eonarheim/TypeState#22]
After looking around NPM for typed FSM packages, I found your awesome package. npms.io shows that this package is insecure because one of your dependencies has a vulnerability, reported by nodesecurity:

https://nodesecurity.io/check/typestate/latest

Check it out.

**Comment by kamranayub** [comment]
There are no dependencies in this package, only for development. Do they
distinguish between dev and non-dev?

**Comment by kamranayub** [comment]
They don't; seems silly if you ask me, consumption of the package would not
result in any issues but they don't say that--just that if you're
developing locally or contributing, maybe there could be (and that seems
doubtful too).

**Comment by eonarheim** [comment]
@hershal Since typestate only has dev-dependencies, and none of them are folded into the final product. We are going to ignore this for now.
