### ISSUE TITLE
Support async transition

### ISSUE THREAD

**Issue by alex-knyazev** [eonarheim/TypeState#30]
It is very good library, but i need to have more powrful control on function:

````
onEnter(state: T, callback: (from?: T, event?: any) => boolean): FiniteStateMachine<T>;
````

It is very good to be: 
````
type SyncFunction = callback: (from?: T, event?: any) => boolean 
Type AsyncFunction =  callback: (from?: T, event?: any) => Promise<boolean> 
onEnter(state: T, callback: SyncFunction | AsyncFunction  ): FiniteStateMachine<T>

````

**Comment by stefnotch** [comment]
So, in the case of an async transition, it shouldn't enter/exit the state until the promise finishes?

Would async functions also make sense here and what should their behaviour be?
```
on(state: T, callback: (from?: T, event?: any) => any): FiniteStateMachine<T> 
```

I would be willing to implement it and create a PR.

**Comment by alex-knyazev** [comment]
@stefnotch  
I think in case of onEnter promise must be resolved to go to new state.
But in case of 'on' it isn;t required

**Comment by eonarheim** [comment]
@stefnotch Async transitions would be an excellent addition! I would gladly accept such a PR!

@alex-knyazev Agreed, I would expect `onEnter` to require the promise to resolve before entering the new state. `on()` does not limit state transition so fire and forget is okay there.
