### ISSUE TITLE
onEnter default return value to true

### ISSUE THREAD

**Issue by stefnotch** [eonarheim/TypeState#31]
`onEnter` expects a boolean return value. If it's `false`, TypeState does not enter the state. If it's `true` TypeState enters the state.

However, if it's `undefined`, which happens if the user simply didn't return anything, TypeState will interpret it as `false` and thus, not enter the state. This is usually not what the user intended to happen.

Example:
```typescript
fsm.onEnter(Elevator.DoorsClosed, (from: Elevator)=>{
   setupGroovyElevatorMusic();
   // Since this doesn't return true, the doors will never close
});
```

My suggestion would be to default to `true` if the return value is `undefined`. However, in some cases this could also result in undesired behaviour.

**Comment by eonarheim** [comment]
I think the default of true here is probably more desired given your example. Another option may be to require an explicit return of boolean from the callback to warn users at compile time, which avoid the change in default behavior but gives the developer warning.
