### ISSUE TITLE
Wrong ts type for callbacks in onEnter/onExit/onInvalidTransition

### ISSUE THREAD

**Issue by AndersCan** [eonarheim/TypeState#38]
onEnter (and other functions with callbacks) look like this:
```ts
public onEnter(state: T, callback: (from?: T, event?: any) => ... {...}
```
From reading the code, I think it should be: `callback: (from: T, event?: any)` as callback is always called with either `state` or `this.currentState`. If the `?` is correct I think the docs should mention this :) 

Made a [playground](https://www.typescriptlang.org/play?target=1#code/AQMwrgdgxgLglgewsJBRCMCmAnAFFAQwBsiAjAqAawC5hcRsEBbAflojCdJwEpgBeAHzAAbgjgATHgG8AsAChgSpYRLkquPgHotwboTABnTMADkDZqeBxDKAA7wkxADTAYACxvXbxIggDumBIAdArKKr7qlLgAjDxhAL4KYeDQjshMAJ4AwpEUlDG4AB7snNzYfNLASYqpsIgZOXlUAEzFbMAcXLzAVTVhaBg4uFm5avlxwDpumXYmOIzYAxDoWHijzZQtPEA) showing the issue.

Let me know if I should make a PR with these changes :)

**Comment by eonarheim** [comment]
Hi @AndersCan thanks for the issue!

You are right, the `from` argument should always be populated on transition.

Definitely would accept a PR to this effect :+1:
